controller_manage_ns: ''
controller_list:
  - name: mobilearmbot/mobilearmbot_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_link1_joint
      - arm_link2_joint
      - arm_link3_joint
  - name: mobilearmbot/mobilearmbot_claw_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_end_effector_joint
      - right_end_effector_joint
