controller_list:
  - name: fake_mobilearmbot_arm_controller
    joints:
      - arm_link1_joint
      - arm_link2_joint
      - arm_link3_joint
  - name: fake_mobilearmbot_claw_controller
    joints:
      - left_end_effector_joint
      - right_end_effector_joint