mobilearmbot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000
  mobilearmbot_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - arm_link1_joint
      - arm_link2_joint
      - arm_link3_joint
  mobilearmbot_claw_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - left_end_effector_joint
      - right_end_effector_joint
