controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_link1_joint
      - arm_link2_joint
      - arm_link3_joint
  - name: end_effector_gripper
    action_ns: gripper_action
    type: GripperCommand
    default: true
    parallel: true
    joints:
      - left_end_effector_joint
      - right_end_effector_joint
