<?xml version="1.0"?>
<robot name="mobilearmbot" xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find mobilearmbot_description)/urdf/colours.xacro"/>
	<xacro:include filename="$(find mobilearmbot_description)/urdf/mobilearmbot.gazebo.xacro"/> 
	<xacro:include filename="$(find mobilearmbot_description)/urdf/inertias.xacro"/>

	<!-- Constants for drivebase -->
	<xacro:property name="base_length" value="0.3"/>
	<xacro:property name="base_width" value="0.3"/>
	<xacro:property name="base_height" value="0.15"/>
	<xacro:property name="base_mass" value="3.0"/>

	<!-- Constants & definition for the four wheels -->
	<xacro:property name="wheel_diam" value="0.1"/>
	<xacro:property name="wheel_length" value="0.05"/>
	<xacro:property name="wheel_mass" value="1"/>
	<xacro:property name="wheel_base_offset" value="0.02"/>
	<xacro:property name="pi" value="3.1415"/>
	<xacro:property name="wheel_df" value="0.0"/>

	<xacro:macro name="wheel_link_description">
		<visual>
			<origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_diam/2.0}"/>
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_diam/2.0}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${wheel_mass}"/>
			<xacro:cylinder_inertia mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_diam/2.0}"/>
		</inertial>
	</xacro:macro>

	<!-- Constants for laser scan-->
	<xacro:property name="scan_length" value="0.05"/>
	<xacro:property name="scan_width" value="0.05"/>
	<xacro:property name="scan_height" value="0.05"/>
	<xacro:property name="scan_mass" value="0.1"/>

	<!-- Constants for arm links -->
	<xacro:property name="link_radii" value="0.05"/> <!-- All links will have the same radius -->
	<xacro:property name="arm_link1_length" value="0.3"/>
	<xacro:property name="arm_link2_length" value="0.4"/>
	<xacro:property name="arm_link1_mass" value="1.2"/>
	<xacro:property name="arm_link2_mass" value="1.6"/>
	<xacro:property name="arm_link3_length" value="0.2"/>
	<xacro:property name="arm_link3_mass" value="0.8"/>
	
	<xacro:macro name="Transmission" params="joint n">
		<transmission name="tran${n}">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${joint}">
				<hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
			</joint>
			<actuator name="motor${n}">
				<hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
			</actuator>
		</transmission>
	</xacro:macro>

	<!-- Constants for end effector -->
	<xacro:property name="end_effector_length" value="0.1"/>
	<xacro:property name="end_effector_width" value="0.05"/>
	<xacro:property name="end_effector_height" value="0.01"/>
	<xacro:property name="end_effector_mass" value="0.1"/>

	<!-- Base link --> 
	<link name="base_link">
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
			<material name="white"/>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${base_mass}"/>
			<xacro:box_inertia mass="${base_mass}" length="${base_length}" width="${base_width}" height="${base_height}"/>
		</inertial>	
	</link>

	<!-- Right front wheel -->
	<link name="right_front_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="right_front_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_front_wheel"/>
		<origin xyz="${base_length/3.0} ${-base_width/2.0 - wheel_base_offset} ${-base_height/2.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="${wheel_df}"/>
	</joint>

	<!-- Right back wheel -->
	<link name="right_back_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="right_back_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_back_wheel"/>
		<origin xyz="${-base_length/3.0} ${-base_width/2.0 - wheel_base_offset} ${-base_height/2.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="${wheel_df}"/>
	</joint>

	<!-- Left front wheel -->
	<link name="left_front_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="left_front_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_front_wheel"/>
		<origin xyz="${base_length/3.0} ${base_width/2.0 + wheel_base_offset} ${-base_height/2.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="${wheel_df}"/>
	</joint>

	<!-- Left back wheel -->
	<link name="left_back_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="left_back_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_back_wheel"/>
		<origin xyz="${-base_length/3.0} ${base_width/2.0 + wheel_base_offset} ${-base_height/2.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="${wheel_df}"/>
	</joint>

	<link name="base_scan">
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="${scan_length} ${scan_width} ${scan_height}"/>
			</geometry>
			<material name="blue"/>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="${scan_length} ${scan_width} ${scan_height}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${scan_mass}"/>
			<xacro:box_inertia mass="${scan_mass}" length="${scan_length}" width="${scan_width}" height="${scan_height}"/>
		</inertial>
	</link>
	<joint name="base_scan_joint" type="fixed">
		<parent link="base_link"/>
		<child link="base_scan"/>
		<origin xyz="0.1 0 ${scan_height/2.0 + base_height/2.0}" rpy="0 0 0"/>
	</joint>

	<link name="arm_link1">
		<visual>
			<origin rpy="0 0 0" xyz="0 0 ${arm_link1_length/2.0}"/>
			<geometry>
				<cylinder length="${arm_link1_length}" radius="${link_radii}"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 ${arm_link1_length/2.0}"/>
			<geometry>
				<cylinder length="${arm_link1_length}" radius="${link_radii}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${arm_link1_mass}"/>
			<xacro:cylinder_inertia mass="${arm_link1_mass}" length="${arm_link1_length}" radius="${link_radii}"/>
		</inertial>
	</link>
	<joint name="arm_link1_joint" type="continuous">
		<parent link="base_link"/>
		<child link="arm_link1"/>
		<origin rpy="0 0 0" xyz="${-base_height/2.0} 0 ${base_height/2.0}"/>
		<axis xyz="0 0 1"/>
	</joint>
	<xacro:Transmission joint="arm_link1_joint" n="0"/>

	<link name="arm_link2">
		<visual>
			<origin rpy="0 0 0" xyz="0 0 ${arm_link2_length/2.0}"/>
			<geometry>
				<cylinder length="${arm_link2_length}" radius="${link_radii}"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 ${arm_link2_length/2.0}"/>
			<geometry>
				<cylinder length="${arm_link2_length}" radius="${link_radii}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${arm_link2_mass}"/>
			<xacro:cylinder_inertia mass="${arm_link2_mass}" length="${arm_link2_length}" radius="${link_radii}"/>
		</inertial>
	</link>

	<joint name="arm_link2_joint" type="continuous">
		<parent link="arm_link1"/>
		<child link="arm_link2"/>
		<origin rpy="0 ${pi/2} 0" xyz="0 0 ${arm_link1_length}"/>
		<axis xyz="0 1 0"/>
	</joint>
	<xacro:Transmission joint="arm_link2_joint" n="1"/>

	<link name="arm_link3">
		<visual>
			<origin rpy="0 0 0" xyz="0 0 ${arm_link3_length/2.0}"/>
			<geometry>
				<cylinder length="${arm_link3_length}" radius="${link_radii}"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 ${arm_link3_length/2.0}"/>
			<geometry>
				<cylinder length="${arm_link3_length}" radius="${link_radii}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${arm_link3_mass}"/>
			<xacro:cylinder_inertia mass="${arm_link3_mass}" length="${arm_link3_length}" radius="${link_radii}"/>
		</inertial>
	</link>
	<joint name="arm_link3_joint" type="continuous">
		<parent link="arm_link2"/>
		<child link="arm_link3"/>
		<origin rpy="0 ${pi/2} 0" xyz="0 0 ${arm_link2_length}"/>
		<axis xyz="0 1 0"/>
	</joint>
	<xacro:Transmission joint="arm_link3_joint" n="2"/>

	<link name="left_end_effector">
		<visual>
			<origin rpy="${pi/2} ${pi/2} 0" xyz="0 0 ${end_effector_length/2}"/>
			<geometry>
				<box size="${end_effector_length} ${end_effector_width} ${end_effector_height}"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="${pi/2} ${pi/2} 0" xyz="0 0 ${end_effector_length/2}"/>
			<geometry>
				<box size="${end_effector_length} ${end_effector_width} ${end_effector_height}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${end_effector_mass}"/>
			<xacro:box_inertia mass="${end_effector_mass}" length="${end_effector_length}" width="${end_effector_width}" height="${end_effector_height}"/>
		</inertial>
	</link>

	<joint name="left_end_effector_joint" type="continuous">
		<parent link="arm_link3"/>
		<child link="left_end_effector"/>
		<origin rpy="0 0 0" xyz="0 ${link_radii} ${arm_link3_length}"/>
		<axis xyz="0 1 0"/>
	</joint>
	<xacro:Transmission joint="left_end_effector_joint" n="3"/>

	<link name="right_end_effector">
		<visual>
			<origin rpy="${pi/2} ${pi/2} 0" xyz="0 0 ${end_effector_length/2}"/>
			<geometry>
				<box size="${end_effector_length} ${end_effector_width} ${end_effector_height}"/>
			</geometry>
		</visual>
		<collision>
                        <origin rpy="${pi/2} ${pi/2} 0" xyz="0 0 ${end_effector_length/2}"/>
                        <geometry>
                                <box size="${end_effector_length} ${end_effector_width} ${end_effector_height}"/>
                        </geometry>
		</collision>
                <inertial>
                        <mass value="${end_effector_mass}"/>
                        <xacro:box_inertia mass="${end_effector_mass}" length="${end_effector_length}" width="${end_effector_width}" height="${end_effector_height}"/>
                </inertial>
	</link>

	<joint name="right_end_effector_joint" type="continuous">
		<parent link="arm_link3"/>
		<child link="right_end_effector"/>
		<origin rpy="0 0 0" xyz="0 ${-link_radii} ${arm_link3_length}"/>
		<axis xyz="0 1 0"/>
	</joint>
	<xacro:Transmission joint="right_end_effector_joint" n="4"/>

</robot>
