<?xml version="1.0"?>
<robot name="mobilearmbot" xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find mobilearmbot_description)/urdf/colours.xacro"/>

	<xacro:property name="base_length" value="0.3"/>
	<xacro:property name="base_width" value="0.3"/>
	<xacro:property name="base_height" value="0.15"/>
	<xacro:property name="base_mass" value="3.0"/>

	<xacro:property name="wheel_diam" value="0.1"/>
	<xacro:property name="wheel_length" value="0.05"/>
	<xacro:property name="wheel_mass" value="0.1"/>
	<xacro:property name="pi" value="3.1415"/>

	<xacro:macro name="wheel_link_description">
		<visual>
			<origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_diam/2.0}"/>
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_diam/2.0}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${wheel_mass}"/>
			<inertia ixx="${wheel_mass * (3*wheel_diam*wheel_diam/4.0 + wheel_length*wheel_length)/12.0}" 
				ixy="0.0" ixz="0.0" 
				iyy="${wheel_mass * (3*wheel_diam*wheel_diam/4.0 + wheel_length*wheel_length)/12.0}" 
				iyz="0.0" izz="${0.5*wheel_mass*wheel_diam*wheel_diam/4.0}"/>
		</inertial>
	</xacro:macro>

	<!-- Base link --> 
	<link name="base_link">
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
			<material name="white"/>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${base_mass}"/>
			<inertia ixx="${base_mass * (base_height*base_height + base_length*base_length)/12.0}" 
				ixy="0.0" ixz="0.0" 
				iyy="${base_mass * (base_width*base_width + base_length*base_length)/12.0}" 
				iyz="0.0" izz="${base_mass * (base_width*base_width + base_height*base_height)/12.0}"/>
		</inertial>	
	</link>

	<!-- Right front wheel -->
	<link name="right_front_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="right_front_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_front_wheel"/>
		<origin xyz="0.075 -0.155 -0.075" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
	</joint>
	<gazebo reference="right_front_wheel">
		<mu1 value="0.1"/>
		<mu2 value="0.1"/>
		<kp value="10000.0"/>
		<kd value="1.0"/>
		<material>Gazebo/Black</material>
	</gazebo>

	<!-- Right back wheel -->
	<link name="right_back_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="right_back_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_back_wheel"/>
		<origin xyz="-0.075 -0.155 -0.075" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
	</joint>
        <gazebo reference="right_back_wheel">
                <mu1 value="0.1"/>
                <mu2 value="0.1"/>
                <kp value="10000.0"/>
                <kd value="1.0"/>
                <material>Gazebo/Black</material>
        </gazebo>

	<!-- Left front wheel -->
	<link name="left_front_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="left_front_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_front_wheel"/>
		<origin xyz="0.075 0.155 -0.075" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
	</joint>
        <gazebo reference="left_front_wheel">
                <mu1 value="0.1"/>
                <mu2 value="0.1"/>
                <kp value="10000.0"/>
                <kd value="1.0"/>
                <material>Gazebo/Black</material>
        </gazebo>

	<!-- Left back wheel -->
	<link name="left_back_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="left_back_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_back_wheel"/>
		<origin xyz="-0.075 0.155 -0.075" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
	</joint>
        <gazebo reference="left_back_wheel">
                <mu1 value="0.1"/>
                <mu2 value="0.1"/>
                <kp value="10000.0"/>
                <kd value="1.0"/>
                <material>Gazebo/Black</material>
        </gazebo>

	<link name="laserscan">
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="0.05 0.05 0.05"/>
			</geometry>
			<material name="blue"/>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="0.05 0.05 0.05"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="0.01"/>
			<inertia ixx="1.67e-7" iyy="1.67e-7" izz="1.67e-7" ixy="0" ixz="0" iyz="0"/>
		</inertial>
	</link>
	<joint name="laserscan_joint" type="fixed">
		<parent link="base_link"/>
		<child link="laserscan"/>
		<origin xyz="0.1 0 0.10" rpy="0 0 0"/>
	</joint>
	<gazebo reference="laserscan">
		<material>Gazebo/Black</material>
		<sensor type="ray" name="laserscan1">
			<pose>0 0 0 0 0 0</pose>
			<visualize>false</visualize>
			<update_rate>10</update_rate>
			<ray>
				<scan>
					<horizontal>
						<samples>360</samples>
						<resolution>1</resolution>
						<min_angle>0.0</min_angle>
						<max_angle>6.28</max_angle>
					</horizontal>
				</scan>
				<range>
					<min>0.2</min>
					<max>30.0</max>
					<resolution>0.015</resolution>
				</range>
				<noise>
					<type>gaussian</type>
					<mean>0</mean>
					<stddev>0.01</stddev>
				</noise>
			</ray>
			<plugin name="mobilearmbot_laserscan_controller" filename="libgazebo_ros_laser.so">
				<topicName>scan</topicName>
				<frameName>base_scan</frameName>
			</plugin>
		</sensor>
	</gazebo>

	<gazebo>
		<plugin name="mobilearmbot_controller" filename="libgazebo_ros_skid_steer_drive.so">
			<updateRate>30.0</updateRate>
			<robotNamespace>/</robotNamespace>
			<leftFrontJoint>left_front_wheel_joint</leftFrontJoint>
			<rightFrontJoint>right_front_wheel_joint</rightFrontJoint>
			<leftRearJoint>left_back_wheel_joint</leftRearJoint>
			<rightRearJoint>right_back_wheel_joint</rightRearJoint>
			<wheelSeparation>0.3</wheelSeparation>
			<wheelDiameter>0.1</wheelDiameter>
			<robotBaseFrame>base_link</robotBaseFrame>
			<torque>20</torque>
			<topicName>cmd_vel</topicName>
			<odometryTopic>odom</odometryTopic>
			<odometryFrame>odom</odometryFrame>
			<odometrySource>world</odometrySource>
			<publishOdomTF>true</publishOdomTF>
			<publishWheelJointState>true</publishWheelJointState>
			<broadcastTF>true</broadcastTF>
		</plugin>
	</gazebo>
</robot>
