<?xml version="1.0"?>
<robot name="mobilearmbot" xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find mobilearmbot_description)/urdf/colours.xacro"/>
	<xacro:include filename="$(find mobilearmbot_description)/urdf/mobilearmbot.gazebo.xacro"/> 

	<!-- Constants for drivebase -->
	<xacro:property name="base_length" value="0.3"/>
	<xacro:property name="base_width" value="0.3"/>
	<xacro:property name="base_height" value="0.15"/>
	<xacro:property name="base_mass" value="3.0"/>

	<!-- Constants & definition for the four wheels -->
	<xacro:property name="wheel_diam" value="0.1"/>
	<xacro:property name="wheel_length" value="0.05"/>
	<xacro:property name="wheel_mass" value="1"/>
	<xacro:property name="wheel_base_offset" value="0.02"/>
	<xacro:property name="pi" value="3.1415"/>
	<xacro:property name="wheel_df" value="0.0"/>

	<xacro:macro name="wheel_link_description">
		<visual>
			<origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_diam/2.0}"/>
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_diam/2.0}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${wheel_mass}"/>
			<inertia ixx="${wheel_mass * (3*wheel_diam*wheel_diam/4.0 + wheel_length*wheel_length)/12.0}" 
				ixy="0.0" ixz="0.0" 
				iyy="${wheel_mass * (3*wheel_diam*wheel_diam/4.0 + wheel_length*wheel_length)/12.0}" 
				iyz="0.0" izz="${0.5*wheel_mass*wheel_diam*wheel_diam/4.0}"/>
		</inertial>
	</xacro:macro>

	<!-- Constants for laser scan-->
	<xacro:property name="scan_length" value="0.05"/>
	<xacro:property name="scan_width" value="0.05"/>
	<xacro:property name="scan_height" value="0.05"/>
	<xacro:property name="scan_mass" value="0.1"/>

	<!-- Constants for links -->
	<xacro:property name="link1_length" value="0.5"/>
	<xacro:property name="link1_radius" value="0.05"/>

	<!-- Base link --> 
	<link name="base_link">
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
			<material name="white"/>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${base_mass}"/>
			<inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
			<inertia ixx="${base_mass * (base_height*base_height + base_length*base_length)/12.0}" 
				ixy="0.0" ixz="0.0" 
				iyy="${base_mass * (base_width*base_width + base_length*base_length)/12.0}" 
				iyz="0.0" izz="${base_mass * (base_width*base_width + base_height*base_height)/12.0}"/>
		</inertial>	
	</link>

	<!-- Right front wheel -->
	<link name="right_front_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="right_front_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_front_wheel"/>
		<origin xyz="${base_length/3.0} ${-base_width/2.0 - wheel_base_offset} ${-base_height/2.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="${wheel_df}"/>
	</joint>

	<!-- Right back wheel -->
	<link name="right_back_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="right_back_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_back_wheel"/>
		<origin xyz="${-base_length/3.0} ${-base_width/2.0 - wheel_base_offset} ${-base_height/2.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="${wheel_df}"/>
	</joint>

	<!-- Left front wheel -->
	<link name="left_front_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="left_front_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_front_wheel"/>
		<origin xyz="${base_length/3.0} ${base_width/2.0 + wheel_base_offset} ${-base_height/2.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="${wheel_df}"/>
	</joint>

	<!-- Left back wheel -->
	<link name="left_back_wheel">
		<xacro:wheel_link_description />
	</link>
	<joint name="left_back_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_back_wheel"/>
		<origin xyz="${-base_length/3.0} ${base_width/2.0 + wheel_base_offset} ${-base_height/2.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<dynamics damping="${wheel_df}"/>
	</joint>

	<link name="laserscan">
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="${scan_length} ${scan_width} ${scan_height}"/>
			</geometry>
			<material name="blue"/>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="${scan_length} ${scan_width} ${scan_height}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="${scan_mass}"/>
                        <inertia ixx="${scan_mass * (scan_height*scan_height + scan_length*scan_length)/12.0}" 
                                ixy="0.0" ixz="0.0" 
                                iyy="${scan_mass * (scan_width*scan_width + scan_length*scan_length)/12.0}" 
                                iyz="0.0" izz="${scan_mass * (scan_width*scan_width + scan_height*scan_height)/12.0}"/>
		</inertial>
	</link>
	<joint name="laserscan_joint" type="fixed">
		<parent link="base_link"/>
		<child link="laserscan"/>
		<origin xyz="0.1 0 0.10" rpy="0 0 0"/>
	</joint>
</robot>
